--	Start of HSNG_SCTY_ROOT

CREATE SCHEMA IF NOT EXISTS DB_HSNG_SCTY_ROOT;

CREATE TABLE IF NOT EXISTS HSNG_SCTY_ROOT
(
    HSNG_SCTY_IDEN		VARCHAR(36)		PRIMARY KEY,
    HSNG_SCTY_NAME		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_REGN_NMBR	VARCHAR(255)	UNIQUE NOT NULL,
    HSNG_SCTY_REGN_DATE	BIGINT			NOT NULL,
    HSNG_SCTY_ADDR_STRT	VARCHAR(255)	NOT NULL,
    HSNG_SCTY_ADDR_AREA	VARCHAR(255)	NOT NULL,
    HSNG_SCTY_ADDR_CITY	VARCHAR(255)	NOT NULL,
    HSNG_SCTY_ADDR_STTE	VARCHAR(255)	NOT NULL,
    HSNG_SCTY_ADDR_CTRY	VARCHAR(255)	NOT NULL,
    HSNG_SCTY_ADDR_PINC	VARCHAR(10)		NOT NULL
);

CREATE TABLE IF NOT EXISTS HSNG_SCTY_OFFC_BRRS
(
    HSNG_SCTY_OFFC_BRRS_REGN_NMBR		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_OFFC_BRRS_TITL			VARCHAR(255)	NOT NULL,
    HSNG_SCTY_OFFC_BRRS_SEQN_NMBR		INT 			NOT NULL,
    HSNG_SCTY_OFFC_BRRS_NAME_FRST		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_OFFC_BRRS_NAME_MIDL		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_OFFC_BRRS_NAME_LAST		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_OFFC_BRRS_DATE_STRT		BIGINT			NOT NULL,
    HSNG_SCTY_OFFC_BRRS_DATE_FNSH		BIGINT,
    HSNG_SCTY_OFFC_BRRS_CNTC_NMBR		BIGINT			NOT NULL,
    HSNG_SCTY_OFFC_BRRS_CNTC_MAIL		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_OFFC_BRRS_CNTC_WTSP		BIGINT			NOT NULL,
    PRIMARY KEY (HSNG_SCTY_OFFC_BRRS_REGN_NMBR, HSNG_SCTY_OFFC_BRRS_TITL, HSNG_SCTY_OFFC_BRRS_SEQN_NMBR),
	FOREIGN KEY (HSNG_SCTY_OFFC_BRRS_REGN_NMBR) REFERENCES HSNG_SCTY_ROOT(HSNG_SCTY_REGN_NMBR)
 );

CREATE TABLE IF NOT EXISTS HSNG_SCTY_SCTN
(
    HSNG_SCTY_SCTN_REGN_NMBR			VARCHAR(255)	PRIMARY KEY,
    HSNG_SCTY_SCTN_TOTL					INT 			NOT NULL,
	FOREIGN KEY (HSNG_SCTY_SCTN_REGN_NMBR) REFERENCES HSNG_SCTY_ROOT(HSNG_SCTY_REGN_NMBR)
 );

CREATE TABLE IF NOT EXISTS HSNG_SCTY_SCTN_DTLS
(
    HSNG_SCTY_SCTN_DTLS_REGN_NMBR		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_SCTN_DTLS_NAME			VARCHAR(255)	NOT NULL,
    HSNG_SCTY_SCTN_DTLS_FLRS			BIGINT			NOT NULL,
    PRIMARY KEY (HSNG_SCTY_SCTN_DTLS_REGN_NMBR, HSNG_SCTY_SCTN_DTLS_NAME),
	FOREIGN KEY (HSNG_SCTY_SCTN_DTLS_REGN_NMBR) REFERENCES HSNG_SCTY_ROOT(HSNG_SCTY_REGN_NMBR)
 );

CREATE TABLE IF NOT EXISTS HSNG_SCTY_FLRS
(
    HSNG_SCTY_FLRS_REGN_NMBR		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_FLRS_SCTN_NAME		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_FLRS_FLOR_NMBR		BIGINT			NOT NULL,
    PRIMARY KEY (HSNG_SCTY_FLRS_REGN_NMBR, HSNG_SCTY_FLRS_SCTN_NAME, HSNG_SCTY_FLRS_FLOR_NMBR),
	FOREIGN KEY (HSNG_SCTY_FLRS_REGN_NMBR, HSNG_SCTY_FLRS_SCTN_NAME) REFERENCES HSNG_SCTY_SCTN_DTLS(HSNG_SCTY_SCTN_DTLS_REGN_NMBR, HSNG_SCTY_SCTN_DTLS_NAME)
 );

CREATE TABLE IF NOT EXISTS HSNG_SCTY_APMT
(
    HSNG_SCTY_APMT_REGN_NMBR		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_APMT_SCTN_NAME		VARCHAR(255)	NOT NULL,
    HSNG_SCTY_APMT_FLOR_NMBR		BIGINT			NOT NULL,
    HSNG_SCTY_APMT_NMBR				BIGINT			NOT NULL,
    HSNG_SCTY_APMT_SIZE				BIGINT			NOT NULL,
    HSNG_SCTY_APMT_SIZE_UNIT		VARCHAR(255)	NOT NULL,
    
    PRIMARY KEY (HSNG_SCTY_APMT_REGN_NMBR, HSNG_SCTY_APMT_SCTN_NAME, HSNG_SCTY_APMT_FLOR_NMBR, HSNG_SCTY_APMT_NMBR),
	FOREIGN KEY (HSNG_SCTY_APMT_REGN_NMBR, HSNG_SCTY_APMT_SCTN_NAME, HSNG_SCTY_APMT_FLOR_NMBR) REFERENCES HSNG_SCTY_FLRS(HSNG_SCTY_FLRS_REGN_NMBR, HSNG_SCTY_FLRS_SCTN_NAME, HSNG_SCTY_FLRS_FLOR_NMBR)
 );

