# Use the official MySQL 8.0 base image
FROM mysql:8.0

# Set environment variables for the MySQL root password and a default database
ENV MYSQL_ROOT_PASSWORD=rootPassword^
ENV MYSQL_DATABASE=MYSQL_DB_HSNG_SCTY_ROOT^
ENV MYSQL_USER=hsngSctyRootUser^
ENV MYSQL_PASSWORD=userPassword^

# Expose the default MySQL port
EXPOSE 3306