POST http://localhost:4000/hsng-scty-root
Content-Type: application/json

{
	"hsngSctyName": "Sangini Epitome",
	"hsngSctyRegnNmbr": "REG/SRT/SA(HAA) 12345/2023",
	"hsngSctyRegnDate": 1697346000000,
	"hsngSctyAddrStrt": "Bhatha Main Road",
	"hsngSctyAddrArea": "Bhatha",
	"hsngSctyAddrCity": "Surat",
	"hsngSctyAddrStte": Gujarat",
	"hsngSctyAddrCtry": "India",
	"hsngSctyAddrPINC": "395009"
}