GET:

	http://localhost:4000/hsng-scty-root/all
	http://localhost:4000/hsng-scty-root/getByPrtlName?hsngSctyNamePrtl=Heights
	http://localhost:4000/hsng-scty-root/getByNameStartsWith?hsngSctyNameStartsWith=Shiv
	http://localhost:4000/hsng-scty-root/getByNameEndsWith?hsngSctyNameEndsWith=Society
	http://localhost:4000/hsng-scty-root/getByPrtlRegnNmbr?hsngSctyRegnNmbrPrtl=02468
	http://localhost:4000/hsng-scty-root/getByRegnNmbrStartsWith?hsngSctyRegnNmbrStartsWith=REG/SRT/SA(HAA) 02468
	http://localhost:4000/hsng-scty-root/getByRegnNmbrEndsWith?hsngSctyRegnNmbrEndsWith=02468/2016
	http://localhost:4000/hsng-scty-root/getByPrtlAddrStrt?hsngSctyAddrStrtPrtl=Magdalla
	http://localhost:4000/hsng-scty-root/getByAddrStrtStartsWith?hsngSctyAddrStrtStartsWith=VIP
	http://localhost:4000/hsng-scty-root/getByAddrStrtEndsWith?hsngSctyAddrStrtEndsWith=Road
	http://localhost:4000/hsng-scty-root/getByAddrArea?hsngSctyAddrArea=Vesu
	http://localhost:4000/hsng-scty-root/getByAddrCity?hsngSctyAddrCity=Surat
	http://localhost:4000/hsng-scty-root/getByAddrCity?hsngSctyAddrCity=Navsari
	http://localhost:4000/hsng-scty-root/getByAddrStte?hsngSctyAddrStte=Gujarat
	http://localhost:4000/hsng-scty-root/getByAddrStte?hsngSctyAddrStte=Maharashtra
	http://localhost:4000/hsng-scty-root/getByAddrCtry?hsngSctyAddrCtry=India
	http://localhost:4000/hsng-scty-root/getByAddrCtry?hsngSctyAddrCtry=Malaysia
	http://localhost:4000/hsng-scty-root/getByAddrPINC?hsngSctyAddrPINC=395007
	http://localhost:4000/hsng-scty-root/getByAddrPINC?hsngSctyAddrPINC=400001

PUT:
	http://localhost:4000/hsng-scty-root/01991734-792d-744f-8d55-8e85ec7bb4fd
	Content-Type: application/json
	
	{
		"hsngSctyIden": "01991734-792d-744f-8d55-8e85ec7bb4fd",
		"hsngSctyName": "Shivalik Heights Co-Operative Housing Service Society",
		"hsngSctyRegnNmbr": "REG/SRT/SA(HAA) 02468/2016",
		"hsngSctyRegnDate": "1472706000000",
		"hsngSctyAddrStrt": "Udhna-Magdalla Rd",
		"hsngSctyAddrArea": "Vesu",
		"hsngSctyAddrCity": "Surat",
		"hsngSctyAddrStte": "Gujarat",
		"hsngSctyAddrCtry": "India",
		"hsngSctyAddrPINC": "395007"
	}
	
DELETE:
	http://localhost:4000/hsng-scty-root/01991734-792d-744f-8d55-8e85ec7bb4fd
	